### ISSUE TITLE
NPE thrown by UriMatchingHandlerInterceptorInterceptor

### ISSUE THREAD

**Issue by rgladwell** [rgladwell/spring-mvc-util#1]
UriMatchingHandlerInterceptorInterceptor is throwing  a NullPointerException on certain MVC requests:

SEVERE: Servlet.service() for servlet dispatcher threw exception

java.lang.NullPointerException
     at java.lang.String.regionMatches(String.java:1297)
     at com.github.spring.mvc.util.handler.HandlerUtils.servletUrlPatternMatch(HandlerUtils.java:32)
     at com.github.spring.mvc.util.handler.UriMatchingHandlerInterceptorInterceptor.invoke(UriMatchingHandlerInterceptorInterceptor.java:46)
     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
     at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
     at $Proxy25.onApplicationEvent(Unknown Source)
     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:303)
     at com.sky.mysky.web.controller.admin.OnlineStatusChangeController.updateOnlineStatus(OnlineStatusChangeController.java:50)
     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
     at java.lang.reflect.Method.invoke(Method.java:597)
     at org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)
     at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:427)
     at org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:415)
     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:788)
     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:717)
     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)
     at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
     at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
     at com.sky.web.filter.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:119)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:128)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
     at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:849)
     at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
     at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:454)
     at java.lang.Thread.run(Thread.java:619)

**Comment by rgladwell** [comment]
This is occurring because the UriMatchingHandlerInterceptorInterceptor is intercepting non-HandlerInterceptor methods: should only intercept preHandle, postHandle and afterCompletion calls.

**Comment by rgladwell** [comment]
Fixed in commit 06481a5665343b27071c
